name 'code_generator'
maintainer 'Optoro'
maintainer_email 'devops@optoro.com'
license 'MIT'
description 'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version '0.0.1'
